packageManagers:
  npm:
    executables:
      - npm
    commands-regex-run:
      - run
      - install
      - update
      - i\s*
    default-cache-dirs:
      - ~/.npm
    commands-regex-modify-cache-dir:
      - ^config set prefix (\S+)\s*

  pip:
    executables:
      - pip
    commands-regex-run:
      - .*install.*
      - .*download.*
    default-cache-dirs:
      - ~/.cache/pip
    anti-cache-options:
      - --no-cache
      - --no-cache-dir

  apt:
    executables:
      - apt
      - apt-get
    commands-regex-run:
      - .*install.*
      - .*update.*
    default-cache-dirs:
      - /var/lib/apt
      - /var/cache/apt
    additional-pre-commands:
      - rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

  go:
    executables:
      - go
    commands-regex-run:
      - .*build.*
      - .*get.*
      - .*install.*
    default-cache-dirs:
      - ~/.cache/go-build

  maven:
    executables:
      - mvn
    commands-regex-run:
      - .+
    default-cache-dirs:
      - ~/.m2/repository

anti-cache-commands-regex:
  - ^rm\s+-r\S*\s+/var/lib/apt[\S\s]*$
  - ^rm\s+-r\S*\s+/var/cache/apt[\S\s]*$
  - ^rm\s+-r\S*\s+/root/.npm[\S\s]*$
  - ^npm\s+cache\s+clean$
