

# syntax = docker/dockerfile:1.3

FROM ubuntu:20.04
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt \
  apt update && apt-get --no-install-recommends install -y gcc
